import { StatisticsType } from "@/components/molecules/statistics/type";
import Character from "@/components/organisms/character";
import mock from "@/mock/statistics.json";
import styles from "@/styles/Home.module.scss";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const statisticsMock = mock as StatisticsType;
  const [statistics, setStatistics] = useState<StatisticsType>([]);

  useEffect(() => {
    setStatistics(statisticsMock);
  }, [statisticsMock]);

  return (
    <div className={styles.container}>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/newCharacter">Créer un personnage</Link>
      <Character statistics={statistics} />
    </div>
  );
};

export default Home;
